name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t awabamjad/wordreversalfrontend:latest .
          docker push awabamjad/wordreversalfrontend:latest
